In [1]:
import numpy as np
from hmmlearn.hmm import MultinomialHMM 
# Other options are GaussianHMM - whose initial probabilities will be from a normal distribution
# Initial probabilities for MultinomialHMM will be categorical

We shall keep only 2 states - A and B

In [4]:
start_prob = np.array([0.5,0.5]) # Both states have same probability pi_1 and pi_2
trans_mat = np.array([
    [0.7, 0.3], # A --> A, A --> B
    [0.3, 0.7]  # B --> A, B --> B
])
start_prob, trans_mat

(array([0.5, 0.5]),
 array([[0.7, 0.3],
        [0.3, 0.7]]))

For multinomial HMM, we need covariance as well

In [3]:
covar = np.array([
    [0.9, 0.1],
    [0.2, 0.8]
])
covar

array([[0.9, 0.1],
       [0.2, 0.8]])

`n_components` = number of states

`startprob_prior` = starting probability (stationary probability)

`transmat_prior` = Transition probabilitiy matrix

In [14]:
model = MultinomialHMM(n_components=2, startprob_prior=start_prob, transmat_prior=trans_mat)

In [15]:
model.transmat_prior

array([[0.7, 0.3],
       [0.3, 0.7]])

In [16]:
# Set of observations
X = [
    [0,0,1,0],
    [0,0,0,0],
    [1,1,1,0],
    [0,0,1,1]
]

In [17]:
model.fit(X)

MultinomialHMM(n_components=2, random_state=RandomState(MT19937) at 0x112868B40,
               startprob_prior=array([0.5, 0.5]),
               transmat_prior=array([[0.7, 0.3],
       [0.3, 0.7]]))

In [18]:
model.transmat_

array([[0.93675852, 0.06324148],
       [0.20992109, 0.79007891]])

In [21]:
prob = model.decode(np.array([0,1,0,1]).reshape(-1,1))
prob

(-3.8399560562810073, array([1, 0, 0, 0]))

In [22]:
np.exp(prob[0]) # The probability of the sequence 0,1,0,1

0.021494545874620487

Generating new samples

In [23]:
X,Z = model.sample(100)
print(X) # X : array, shape (n_samples, n_features) - Feature matrix.

[[1]
 [1]
 [0]
 [0]
 [1]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [1]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [1]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [1]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [0]
 [0]
 [1]
 [0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [1]
 [0]
 [1]
 [1]
 [1]]


In [24]:
print(Z) # State sequence produced by model

[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 1 1 1 0 0 0 0 0 0 1 1 1 1 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
